#!/bin/bash
#COBALT -n 2
#COBALT -t 20
#COBALT --mode script
#COBALT -A radix-io
#COBALT -q ibleaf3-debug

echo "## MPI (one way, double the latency for round trip):"
mpirun -f $COBALT_NODEFILE -n 2 ./osu_latency

# NOTE: the CCI tests sometimes either crash or hang unless run in busy-spin 
#       mode on Cooley as of 2018-01-31

# sleep 1 
#
# echo "## Margo CCI/VERBS (round trip):"
# mpirun -f $COBALT_NODEFILE -n 2 ./margo-p2p-latency -i 100000 -n cci+verbs://
# echo "## Margo CCI/VERBS (bw):"
# mpirun -f $COBALT_NODEFILE -n 2 ./margo-p2p-bw -x 1048576 -n cci+verbs:// -c 1 -D 20
# echo "## Margo CCI/VERBS (bw, 8x concurrency):"
# mpirun -f $COBALT_NODEFILE -n 2 ./margo-p2p-bw -x 1048576 -n cci+verbs:// -c 8 -D 20
# sleep 1

echo "## Margo CCI/VERBS (round trip, Hg busy spin):"
mpirun -f $COBALT_NODEFILE -n 2 ./margo-p2p-latency -i 100000 -n cci+verbs:// -t 0,0
echo "## Margo CCI/VERBS (bw, Hg busy spin):"
mpirun -f $COBALT_NODEFILE -n 2 ./margo-p2p-bw -x 1048576 -n cci+verbs:// -c 1 -D 20 -t 0,0
echo "## Margo CCI/VERBS (bw, 8x concurrency, Hg busy spin):"
mpirun -f $COBALT_NODEFILE -n 2 ./margo-p2p-bw -x 1048576 -n cci+verbs:// -c 8 -D 20 -t 0,0


# TODO: mercury-runner freezes at shutdown w/ cci+verbs -- commenting out mercury finalize routines doesn't seem to help
#echo "## Mercury-runner CCI/VERBS (round trip):"
#mpirun -f $COBALT_NODEFILE -n 2 ./mercury-runner -q -c 100000 -l 1 -m c -M -d `pwd` 1 h0=verbs:// h1
