#!/bin/bash
#COBALT -n 2
#COBALT -t 10
#COBALT --mode script
#COBALT -A radix-io
#COBALT -q debug-flat-quad
#COBALT -M carns@mcs.anl.gov

echo "OFI/GNI:"
aprun -n 2 -N 1 ./margo-p2p-latency -i 100000 -n ofi+gni://ipogif0:5000
echo "BMI/TCP:"
aprun -n 2 -N 1 ./margo-p2p-latency -i 100000 -n bmi+tcp://
echo "OFI/TCP (disabled because it hangs as of 8/10/2017):"
# aprun -n 2 -N 1 ./margo-p2p-latency -i 100000 -n ofi+tcp://ipogif0:5000
