#!/bin/bash
#COBALT -n 2
#COBALT -t 20
#COBALT --mode script
#COBALT -A radix-io
#COBALT -q ibleaf3-debug

export FI_FORK_UNSAFE=1

export SPACK_SHELL=bash

. /home/carns/working/src/spack/share/spack/setup-env.sh
spack load -r ssg 

# TODO: why is this necessary?  We should be able to find gcc libraries...
export LD_LIBRARY_PATH="/soft/compilers/gcc/7.1.0/lib64:$LD_LIBRARY_PATH"

# echo "## MPI (one way, double the latency for round trip):"
# mpirun -f $COBALT_NODEFILE -n 2 ./osu_latency

sleep 1 

echo "## Margo OFI/VERBS (round trip, Hg busy spin):"
mpirun -f $COBALT_NODEFILE -n 2 ./margo-p2p-latency -i 100000 -n "ofi+verbs;ofi_rxm://mlx5_0:3339" -t 0,0
echo "## Margo OFI/VERBS (bw, Hg busy spin):"
mpirun -f $COBALT_NODEFILE -n 2 ./margo-p2p-bw -x 1048576 -n "ofi+verbs;ofi_rxm://mlx5_0:3339" -c 1 -D 20 -t 0,0
echo "## Margo OFI/VERBS (bw, 8x concurrency, Hg busy spin):"
mpirun -f $COBALT_NODEFILE -n 2 ./margo-p2p-bw -x 1048576 -n "ofi+verbs;ofi_rxm://mlx5_0:3339" -c 8 -D 20 -t 0,0

# as of 2018-04-10 the "verbs;ofi_rxm" provider does not handle blocking mode
# (wait objects) properly
#
# sleep 1
#
# echo "## Margo OFI/VERBS (round trip):"
# mpirun -f $COBALT_NODEFILE -n 2 ./margo-p2p-latency -i 100000 -n "ofi+verbs;ofi_rxm://"
# echo "## Margo OFI/VERBS (bw):"
# mpirun -f $COBALT_NODEFILE -n 2 ./margo-p2p-bw -x 1048576 -n "ofi+verbs;ofi_rxm://" -c 1 -D 20
# echo "## Margo OFI/VERBS (bw, 8x concurrency):"
# mpirun -f $COBALT_NODEFILE -n 2 ./margo-p2p-bw -x 1048576 -n "ofi+verbs;ofi_rxm://" -c 8 -D 20


# echo "## Mercury-runner CCI/VERBS (round trip):"
# mpirun -f $COBALT_NODEFILE -n 2 ./mercury-runner -q -c 100000 -l 1 -m c -M -d `pwd` 1 h0=verbs;ofi_rxm:// h1
