#!/bin/bash
#COBALT -n 2
#COBALT -t 10
#COBALT --mode script
#COBALT -A radix-io
#COBALT -q ibleaf3-debug

export HG_NEVER_BLOCK=1

echo "## MPI (one way, double the latency for round trip):"
mpirun -f $COBALT_NODEFILE -n 2 ./osu_latency
echo "## Margo CCI/VERBS (round trip):"
mpirun -f $COBALT_NODEFILE -n 2 ./margo-p2p-latency -i 100000 -n verbs://

# echo "## Margo CCI/VERBS (round trip) with diagnostics:"
# mpirun -f $COBALT_NODEFILE -n 2 ./margo-p2p-latency -i 100000 -n verbs:// -d $COBALT_JOBID.diag

# TODO: mercury-runner freezes at shutdown w/ cci+verbs -- commenting out mercury finalize routines doesn't seem to help
#echo "## Mercury-runner CCI/VERBS (round trip):"
#mpirun -f $COBALT_NODEFILE -n 2 ./mercury-runner -q -c 100000 -l 1 -m c -M -d `pwd` 1 h0=verbs:// h1
