#!/bin/bash
#COBALT -n 2
#COBALT -t 10
#COBALT --mode script
#COBALT -A radix-io
#COBALT -q ibleaf3-debug

# NOTE: remmeber to uncomment some stuff in ~/.bashrc for library paths

echo "## MPI (one way, double the latency for round trip):"
mpirun -f $COBALT_NODEFILE -n 2 ./osu_latency
echo "## Margo CCI/VERBS (round trip):"
mpirun -f $COBALT_NODEFILE -n 2 ./margo-p2p-latency -i 100000 -n verbs://
echo "## Margo CCI/VERBS (round trip) with diagnostics:"
mpirun -f $COBALT_NODEFILE -n 2 ./margo-p2p-latency -i 100000 -n verbs:// -d $COBALT_JOBID.diag
echo "## Mercury-runner CCI/VERBS (round trip):"
mpirun -f $COBALT_NODEFILE -n 2 ./mercury-runner -q -c 100000 -l 1 -m c -M -d `pwd` 1 h0=verbs:// h1
