#!/bin/bash
#COBALT -n 2
#COBALT -t 20
#COBALT --mode script
#COBALT -A radix-io
#COBALT -q ibleaf3-debug

# NOTE: as of Jan 31 2018, some of the test programs will hang in non-busy
#       spin mode on cooley with RHEL 6.9.  They work fine with RHEL 7.4 though.
#
# NOTE: origin/master of libfabric also will not compile on RHEL 6.9 at this 
#       either

export FI_FORK_UNSAFE=1

echo "## MPI (one way, double the latency for round trip):"
mpirun -f $COBALT_NODEFILE -n 2 ./osu_latency

sleep 1 

echo "## Margo OFI/VERBS (round trip, Hg busy spin):"
mpirun -f $COBALT_NODEFILE -n 2 ./margo-p2p-latency -i 100000 -n ofi+verbs:// -t 0,0
echo "## Margo OFI/VERBS (bw, Hg busy spin):"
mpirun -f $COBALT_NODEFILE -n 2 ./margo-p2p-bw -x 1048576 -n ofi+verbs:// -c 1 -D 20 -t 0,0
echo "## Margo OFI/VERBS (bw, 8x concurrency, Hg busy spin):"
mpirun -f $COBALT_NODEFILE -n 2 ./margo-p2p-bw -x 1048576 -n ofi+verbs:// -c 8 -D 20 -t 0,0

sleep 1

echo "## Margo OFI/VERBS (round trip):"
mpirun -f $COBALT_NODEFILE -n 2 ./margo-p2p-latency -i 100000 -n ofi+verbs://
echo "## Margo OFI/VERBS (bw):"
mpirun -f $COBALT_NODEFILE -n 2 ./margo-p2p-bw -x 1048576 -n ofi+verbs:// -c 1 -D 20
echo "## Margo OFI/VERBS (bw, 8x concurrency):"
mpirun -f $COBALT_NODEFILE -n 2 ./margo-p2p-bw -x 1048576 -n ofi+verbs:// -c 8 -D 20


#echo "## Mercury-runner CCI/VERBS (round trip):"
#mpirun -f $COBALT_NODEFILE -n 2 ./mercury-runner -q -c 100000 -l 1 -m c -M -d `pwd` 1 h0=verbs:// h1
