/*
 * (C) 2016 The University of Chicago
 * 
 * See COPYRIGHT in top-level directory.
 */
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <assert.h>

#include <mercury.h>
#include <margo.h>

#include "ssg.h"
#include "ssg-internal.h"
#include "swim-fd.h"
#include "swim-fd-internal.h"

/* NOTE: keep these defines in sync with defs in swim.h */
#define hg_proc_swim_member_status_t    hg_proc_uint8_t
#define hg_proc_swim_member_inc_nr_t    hg_proc_uint32_t
MERCURY_GEN_STRUCT_PROC(swim_member_state_t, \
    ((swim_member_inc_nr_t) (inc_nr)) \
    ((swim_member_status_t) (status)));
MERCURY_GEN_STRUCT_PROC(swim_member_update_t, \
    ((ssg_member_id_t) (id)) \
    ((swim_member_state_t) (state)));

/* a swim message is the membership information piggybacked (gossiped)
 * on the ping and ack messages generated by the protocol
 */
typedef struct swim_message_s
{
    ssg_member_id_t source_id;
    swim_member_inc_nr_t source_inc_nr;
    hg_size_t swim_pb_buf_count;
    hg_size_t ssg_pb_buf_count;
    swim_member_update_t swim_pb_buf[SWIM_MAX_PIGGYBACK_ENTRIES]; //TODO: dynamic array?
    ssg_member_update_t ssg_pb_buf[SWIM_MAX_PIGGYBACK_ENTRIES]; //TODO: dynamic array?
} swim_message_t;

/* HG encode/decode routines for SWIM RPCs */
static hg_return_t hg_proc_swim_message_t(
    hg_proc_t proc, void *data);

MERCURY_GEN_PROC(swim_dping_req_t, \
    ((swim_message_t) (msg)));
MERCURY_GEN_PROC(swim_dping_resp_t, \
    ((swim_message_t) (msg)));

MERCURY_GEN_PROC(swim_iping_req_t, \
    ((ssg_member_id_t) (target_id)) \
    ((swim_message_t) (msg)));
MERCURY_GEN_PROC(swim_iping_resp_t, \
    ((swim_message_t) (msg)));

/* SWIM message pack/unpack prototypes */
static void swim_pack_message(
    ssg_group_t *group, swim_message_t *msg);
static void swim_unpack_message(
    ssg_group_t *group, swim_message_t *msg);

DECLARE_MARGO_RPC_HANDLER(swim_dping_recv_ult)
DECLARE_MARGO_RPC_HANDLER(swim_iping_recv_ult)

static hg_id_t swim_dping_rpc_id;
static hg_id_t swim_iping_rpc_id;

void swim_register_ping_rpcs(
    ssg_group_t *group)
{
    assert(group != NULL);

    /* register RPC handlers for SWIM pings */
    swim_dping_rpc_id = MARGO_REGISTER(group->swim_ctx->mid, "swim_dping", swim_dping_req_t,
        swim_dping_resp_t, swim_dping_recv_ult);
    swim_iping_rpc_id = MARGO_REGISTER(group->swim_ctx->mid, "swim_iping", swim_iping_req_t,
        swim_iping_resp_t, swim_iping_recv_ult);

    /* register SSG group data structure with each RPC type */
    /* XXX: this won't work for multiple groups ... */
    margo_register_data(group->swim_ctx->mid, swim_dping_rpc_id, group, NULL);
    margo_register_data(group->swim_ctx->mid, swim_iping_rpc_id, group, NULL);

    return;
}

/********************************
 *       SWIM direct pings      *
 ********************************/

static int swim_send_dping(
    ssg_group_t *group, ssg_member_id_t dping_target_id, hg_addr_t dping_target_addr);

void swim_dping_send_ult(
    void *t_arg)
{
    ssg_group_t *group = (ssg_group_t *)t_arg;
    ssg_member_id_t dping_target_id;
    swim_context_t *swim_ctx;
    int ret;

    assert(group != NULL);
    swim_ctx = group->swim_ctx;
    assert(swim_ctx != NULL);

    dping_target_id = swim_ctx->dping_target_id;
    ret = swim_send_dping(group, swim_ctx->dping_target_id, swim_ctx->dping_target_addr);
    if (ret == 0)
    {
        /* mark this dping req as acked, double checking to make
         * sure we aren't inadvertently ack'ing a ping request
         * for a more recent tick of the protocol
         */
        /* XXX: maybe just use a sequence number? this isn't technically right */
        if(swim_ctx->dping_target_id == dping_target_id)
            swim_ctx->ping_target_acked = 1;
    }

    return;
}

static int swim_send_dping(
    ssg_group_t *group, ssg_member_id_t dping_target_id, hg_addr_t dping_target_addr)
{
    swim_context_t *swim_ctx;
    hg_handle_t handle;
    swim_dping_req_t dping_req;
    swim_dping_resp_t dping_resp;
    hg_return_t hret;
    int ret = -1;

    assert(group != NULL);
    swim_ctx = group->swim_ctx;
    assert(group->swim_ctx != NULL);

    hret = margo_create(swim_ctx->mid, dping_target_addr, swim_dping_rpc_id, &handle);
    if(hret != HG_SUCCESS)
        return(ret);

    SSG_DEBUG(group, "SWIM: send dping req to %lu\n", dping_target_id);

    /* fill the direct ping request with current membership state */
    swim_pack_message(group, &(dping_req.msg));

    /* send a direct ping that expires at the end of the protocol period */
    hret = margo_forward_timed(handle, &dping_req, swim_ctx->prot_period_len);
    if (hret == HG_SUCCESS)
    {
        hret = margo_get_output(handle, &dping_resp);
        if(hret != HG_SUCCESS) goto fini;

        SSG_DEBUG(group, "SWIM: recv dping ack from %lu\n", dping_resp.msg.source_id);
        assert(dping_resp.msg.source_id == dping_target_id);

        /* extract target's membership state from response */
        swim_unpack_message(group, &(dping_resp.msg));

        margo_free_output(handle, &dping_resp);
        ret = 0;
    }
    else if(hret != HG_TIMEOUT)
    {
        fprintf(stderr, "SWIM dping req error (err=%d)\n", hret);
    }

fini:
    margo_destroy(handle);
    return(ret);
}

static void swim_dping_recv_ult(
    hg_handle_t handle)
{
    const struct hg_info *hgi;
    margo_instance_id mid;
    ssg_group_t *group;
    swim_dping_req_t dping_req;
    swim_dping_resp_t dping_resp;
    hg_return_t hret;

    /* get handle info and margo instance */
    hgi = margo_get_info(handle);
    assert(hgi);
    mid = margo_hg_info_get_instance(hgi);
    assert(mid != MARGO_INSTANCE_NULL);

    /* get SSG group */
    group = (ssg_group_t *)margo_registered_data(mid, swim_dping_rpc_id);
    assert(group != NULL);

    hret = margo_get_input(handle, &dping_req);
    if(hret != HG_SUCCESS) goto fini;

    SSG_DEBUG(group, "SWIM: recv dping req from %lu\n", dping_req.msg.source_id);

    /* extract sender's membership state from request */
    swim_unpack_message(group, &(dping_req.msg));

    /* fill the direct ping response with current membership state */
    swim_pack_message(group, &(dping_resp.msg));

    SSG_DEBUG(group, "SWIM: send dping ack to %lu\n", dping_req.msg.source_id);

    /* respond to sender of the dping req */
    margo_respond(handle, &dping_resp);

    margo_free_input(handle, &dping_req);
fini:
    margo_destroy(handle);
    return;
}
DEFINE_MARGO_RPC_HANDLER(swim_dping_recv_ult)

/********************************
 *     SWIM indirect pings      *
 ********************************/

void swim_iping_send_ult(
    void *t_arg)
{
    ssg_group_t *group = (ssg_group_t *)t_arg;
    swim_context_t *swim_ctx;
    ssg_member_id_t iping_target_id;
    hg_addr_t iping_target_addr;
    hg_handle_t handle;
    swim_iping_req_t iping_req;
    swim_iping_resp_t iping_resp;
    hg_return_t hret;

    assert(group != NULL);
    swim_ctx = group->swim_ctx;
    assert(swim_ctx != NULL);

    ABT_rwlock_wrlock(group->lock);
    iping_target_id = swim_ctx->iping_target_ids[swim_ctx->iping_target_ndx];
    iping_target_addr = swim_ctx->iping_target_addrs[swim_ctx->iping_target_ndx];
    swim_ctx->iping_target_ndx++;
    ABT_rwlock_unlock(group->lock);

    hret = margo_create(swim_ctx->mid, iping_target_addr, swim_iping_rpc_id, &handle);
    if(hret != HG_SUCCESS)
        return;

    SSG_DEBUG(group, "SWIM: send iping req to %lu (target=%lu)\n",
        iping_target_id, swim_ctx->dping_target_id);

    /* fill the indirect ping request with target member and current
     * membership state
     */
    iping_req.target_id = swim_ctx->dping_target_id;
    swim_pack_message(group, &(iping_req.msg));

    /* send this indirect ping */
    /* NOTE: the timeout is just the protocol period length minus
     * the dping timeout, which should cause this iping to timeout
     * right at the end of the current protocol period.
     */
    hret = margo_forward_timed(handle, &iping_req,
        (swim_ctx->prot_period_len - swim_ctx->dping_timeout));
    if (hret == HG_SUCCESS)
    {
        hret = margo_get_output(handle, &iping_resp);
        if(hret != HG_SUCCESS) goto fini;

        SSG_DEBUG(group, "SWIM: recv iping ack from %lu (target=%lu)\n",
            iping_resp.msg.source_id, swim_ctx->dping_target_id);

        /* extract target's membership state from response */
        swim_unpack_message(group, &(iping_resp.msg));

        /* mark this iping req as acked, double checking to make
         * sure we aren't inadvertently ack'ing a ping request
         * for a more recent tick of the protocol
         */
        if(swim_ctx->dping_target_id == iping_req.target_id)
            swim_ctx->ping_target_acked = 1;

        margo_free_output(handle, &iping_resp);
    }
    else if(hret != HG_TIMEOUT)
    {
        fprintf(stderr, "SWIM iping req error (err=%d)\n", hret);
    }

fini:
    margo_destroy(handle);
    return;
}

static void swim_iping_recv_ult(hg_handle_t handle)
{
    const struct hg_info *hgi;
    margo_instance_id mid;
    ssg_group_t *group;
    ssg_member_state_t *target_ms;
    swim_iping_req_t iping_req;
    swim_iping_resp_t iping_resp;
    hg_addr_t target_addr;
    hg_return_t hret;
    int ret;

    /* get handle info and margo instance */
    hgi = margo_get_info(handle);
    assert(hgi);
    mid = margo_hg_info_get_instance(hgi);
    assert(mid != MARGO_INSTANCE_NULL);

    /* get SSG group */
    group = (ssg_group_t *)margo_registered_data(mid, swim_dping_rpc_id);
    assert(group != NULL);

    hret = margo_get_input(handle, &iping_req);
    if(hret != HG_SUCCESS) goto fini;

    SSG_DEBUG(group, "SWIM: recv iping req from %lu (target=%lu)\n",
        iping_req.msg.source_id, iping_req.target_id);

    /* extract sender's membership state from request */
    swim_unpack_message(group, &(iping_req.msg));

    /* get the address of the ping target */
    ABT_rwlock_rdlock(group->lock);
    HASH_FIND(hh, group->view.member_map, &iping_req.target_id,
        sizeof(iping_req.target_id), target_ms);
    if(!target_ms)
    {
        ABT_rwlock_unlock(group->lock);
        margo_free_input(handle, &iping_req);
        goto fini;
    }
    hret = margo_addr_dup(mid, target_ms->addr, &target_addr);
    if(hret != HG_SUCCESS)
    {
        ABT_rwlock_unlock(group->lock);
        margo_free_input(handle, &iping_req);
        goto fini;
    }
    ABT_rwlock_unlock(group->lock);

    /* send direct ping to target on behalf of who sent iping req */
    ret = swim_send_dping(group, iping_req.target_id, target_addr);
    if(ret == 0)
    {
        /* if the dping req succeeds, fill the indirect ping
         * response with current membership state
         */
        swim_pack_message(group, &(iping_resp.msg));

        SSG_DEBUG(group, "SWIM: send iping ack to %lu (target=%lu)\n",
            iping_req.msg.source_id, iping_req.target_id);

        /* respond to sender of the iping req */
        margo_respond(handle, &iping_resp);
    }

    margo_addr_free(mid, target_addr);
    margo_free_input(handle, &iping_req);
fini:
    margo_destroy(handle);
    return;
}
DEFINE_MARGO_RPC_HANDLER(swim_iping_recv_ult)

/********************************
 *      SWIM ping helpers       *
 ********************************/

static void swim_pack_message(ssg_group_t *group, swim_message_t *msg)
{
    memset(msg, 0, sizeof(*msg));

    /* fill in self information */
    msg->source_id = group->self_id;
    msg->source_inc_nr = group->swim_ctx->self_inc_nr;

    /* piggyback SWIM & SSG updates on the message */
    msg->swim_pb_buf_count = SWIM_MAX_PIGGYBACK_ENTRIES;
    msg->ssg_pb_buf_count = SWIM_MAX_PIGGYBACK_ENTRIES;
    swim_retrieve_member_updates(group, msg->swim_pb_buf, &msg->swim_pb_buf_count);
    swim_retrieve_ssg_member_updates(group, msg->ssg_pb_buf, &msg->ssg_pb_buf_count);

    return;
}

static void swim_unpack_message(ssg_group_t *group, swim_message_t *msg)
{
    swim_member_update_t sender_update;

    /* apply (implicit) sender update */
    sender_update.id = msg->source_id;
    sender_update.state.status = SWIM_MEMBER_ALIVE;
    sender_update.state.inc_nr = msg->source_inc_nr;
    swim_apply_member_updates(group, &sender_update, 1);

    /* apply SWIM updates */
    if(msg->swim_pb_buf_count > 0)
        swim_apply_member_updates(group, msg->swim_pb_buf, msg->swim_pb_buf_count);

    /* apply SSG updates */
    if(msg->ssg_pb_buf_count > 0)
        ssg_apply_member_updates(group, msg->ssg_pb_buf, msg->ssg_pb_buf_count);

    return;
}

/* manual serialization/deserialization routine for swim messages */
static hg_return_t hg_proc_swim_message_t(hg_proc_t proc, void *data)
{
    swim_message_t *msg = (swim_message_t *)data;
    hg_return_t hret = HG_PROTOCOL_ERROR;
    hg_size_t i;

    switch(hg_proc_get_op(proc))
    {
        case HG_ENCODE:
            hret = hg_proc_ssg_member_id_t(proc, &(msg->source_id));
            if(hret != HG_SUCCESS)
            {
                hret = HG_PROTOCOL_ERROR;
                return hret;
            }
            hret = hg_proc_swim_member_inc_nr_t(proc, &(msg->source_inc_nr));
            if(hret != HG_SUCCESS)
            {
                hret = HG_PROTOCOL_ERROR;
                return hret;
            }
            hret = hg_proc_hg_size_t(proc, &(msg->swim_pb_buf_count));
            if(hret != HG_SUCCESS)
            {
                hret = HG_PROTOCOL_ERROR;
                return hret;
            }
            hret = hg_proc_hg_size_t(proc, &(msg->ssg_pb_buf_count));
            if(hret != HG_SUCCESS)
            {
                hret = HG_PROTOCOL_ERROR;
                return hret;
            }
            for(i = 0; i < msg->swim_pb_buf_count; i++)
            {
                hret = hg_proc_swim_member_update_t(proc, &(msg->swim_pb_buf[i]));
                if(hret != HG_SUCCESS)
                {
                    hret = HG_PROTOCOL_ERROR;
                    return hret;
                }
            }
            for(i = 0; i < msg->ssg_pb_buf_count; i++)
            {
                hret = hg_proc_ssg_member_update_t(proc, &(msg->ssg_pb_buf[i]));
                if(hret != HG_SUCCESS)
                {
                    hret = HG_PROTOCOL_ERROR;
                    return hret;
                }
            }
            break;
        case HG_DECODE:
            hret = hg_proc_ssg_member_id_t(proc, &(msg->source_id));
            if(hret != HG_SUCCESS)
            {
                hret = HG_PROTOCOL_ERROR;
                return hret;
            }
            hret = hg_proc_swim_member_inc_nr_t(proc, &(msg->source_inc_nr));
            if(hret != HG_SUCCESS)
            {
                hret = HG_PROTOCOL_ERROR;
                return hret;
            }
            hret = hg_proc_hg_size_t(proc, &(msg->swim_pb_buf_count));
            if(hret != HG_SUCCESS)
            {
                hret = HG_PROTOCOL_ERROR;
                return hret;
            }
            hret = hg_proc_hg_size_t(proc, &(msg->ssg_pb_buf_count));
            if(hret != HG_SUCCESS)
            {
                hret = HG_PROTOCOL_ERROR;
                return hret;
            }
            for(i = 0; i < msg->swim_pb_buf_count; i++)
            {
                hret = hg_proc_swim_member_update_t(proc, &(msg->swim_pb_buf[i]));
                if(hret != HG_SUCCESS)
                {
                    hret = HG_PROTOCOL_ERROR;
                    return hret;
                }
            }
            for(i = 0; i < msg->ssg_pb_buf_count; i++)
            {
                hret = hg_proc_ssg_member_update_t(proc, &(msg->ssg_pb_buf[i]));
                if(hret != HG_SUCCESS)
                {
                    hret = HG_PROTOCOL_ERROR;
                    return hret;
                }
            }
            break;
        case HG_FREE:
            for(i = 0; i < msg->ssg_pb_buf_count; i++)
            {
                hret = hg_proc_ssg_member_update_t(proc, &(msg->ssg_pb_buf[i]));
                if(hret != HG_SUCCESS)
                {
                    hret = HG_PROTOCOL_ERROR;
                    return hret;
                }
            }
            hret = HG_SUCCESS;
            break;
        default:
            break;
    }

    return(hret);
}
